name: Build and push Docker images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        include:
          - toolchain: acpp
            version: 25.02.0
          - toolchain: clang
            version: 20.1.8
          - toolchain: oneapi
            version: 2024.2.0
          - toolchain: oneapi
            version: 2025.1.1
          # - toolchain: oneapi
          #   version: 2025.2.0
          - toolchain: cuda
            version: 12.3.2
          - toolchain: oneapi-runtime
            version: 2024.2.0
          - toolchain: oneapi-runtime
            version: 2025.1.1
          - toolchain: oneapi-runtime
            version: 2025.2.0

    env:
      REGISTRY: docker.io
      IMAGE_NAME: fbarbari/sycl-ci:${{ matrix.toolchain }}${{ matrix.version }}
      IMAGE_ROOT: ${{ github.workspace }}/${{ matrix.toolchain }}/${{ matrix.version }}

    steps:
      - name: Free disk space
        if: runner.os == 'Linux'
        run: |
          df -h
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli google-cloud-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo docker system prune --all --volumes --force
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          df -h

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker image
        run: |
          cd ${GITHUB_WORKSPACE}/${{ matrix.toolchain }}/${{ matrix.version }}
          docker build -t ${REGISTRY}/${IMAGE_NAME} -f Dockerfile .
      
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: fbarbari
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        id: push
        run: |
          docker push ${REGISTRY}/${IMAGE_NAME}
